### ISSUE TITLE
How to turn on screen using ioctl?

### ISSUE THREAD

**Issue by ghost** [jerome-pouiller/ioctl#1]
Not being a dev or coder, (how) can I use ioctl to reverse these

/sys/class/drm/card0-eDP-1/status -> "connected"
/sys/class/drm/card0-DP-1/status -> "disconnected"

or make both of them "connected"?

**Comment by jerome-pouiller** [comment]
Dear AcarBurak,

On Monday 14 November 2016 07:03:03 AcarBurak wrote:

> Not being a dev or coder, (how) can I use ioctl to reverse these
> 
> /sys/class/drm/card0-eDP-1/status -> "connected"
> /sys/class/drm/card0-DP-1/status -> "disconnected"
> 
> or make both of them "connected"?
> You have to check in DRM API or more specifically in your driver 
> documentation (even if often, source is the only documentation) how it 
> should work.

If there is an ioctl to control this feature, ioctl command may be able 
to control it.

However, in your case, intuitively I would say "status" is updated 
automatically by driver. 

BR,

## 

J�r�me Pouiller, Sysmic
Embedded Linux specialist
http://www.sysmic.fr

**Comment by ghost** [comment]
Thanks for the prompt response.

> However, in your case, intuitively I would say "status" is updated
> automatically by driver.

Yes, I guess so. I've installed Debian Testing on a mid 2010 iMac (amd 4670) and I had to install firmware-linux-nonfree as well (using the open source radeon driver). Yet doing so boots the system to black screen. A kernel bug reporter has solved it by

`echo "on" > /sys/class/drm/card0-DP-1/status`

which doesn't work in my case as another bug communication in freedesktop.org states

> this is how the sysfs interface works. On resume we reset the
> connector state to unknown and send out a uevent to make sure userspace
> reprobes. Once reprobed the connector status will be udpated. sysfs
> interface themselves never cause a probe but only print out the current
> value. To force a probe you need to do ioctls on the drm device.

Hence I'm here! Sorry for being unclear before and for being long-winded now!

**Comment by ghost** [comment]
Well, i gather now that even managing this wouldn't solve my issue. Sorry for the noise.
