### ISSUE TITLE
Another ioctl tool has different features

### ISSUE THREAD

**Issue by daveloyall** [jerome-pouiller/ioctl#5]
Jérôme, I know you've heard of Android's ioctl tool.

Here is the last version of it that seems to exist before it was removed because it is a "convenient tool for attacking buggy kernels", according to an Android developer... :(

https://android.googlesource.com/platform/system/core/+/68285c00334af57d9077648fb408a34643514df5/toolbox/ioctl.c

Perhaps you or one of the people that has stared/forked your ioctl will find this path of inquiry interesting.  Cheers!

**Comment by jerome-pouiller** [comment]
Thank you for the link.
