### ISSUE TITLE
Missing feature: IOCTL for network devices

### ISSUE THREAD

**Issue by Zibri** [jerome-pouiller/ioctl#6]
IOCTL for network devices
 (wlan0 for example or any ethernet device)

You add it or I fork and add it myself?

**Comment by jerome-pouiller** [comment]
I would be glad to receive your patch.

However, since there are no file devices associated to network interfaces, how do you suggest to implement that? We may think about a generic solution since we may want to add support for other kind of resources in future.

**Comment by Zibri** [comment]
Usually the enumeration is done using a socket. You can find everything in iwlist and iwlist sources. I made a small utility like iwlist but independent from any library... now I am not at home. When I have some time I can send you some snippets if you need.

-------- Messaggio originale --------
Da: Jérôme Pouiller <notifications@github.com> 
Data:07/05/2018  10:34  (GMT+01:00) 
A: jerome-pouiller/ioctl <ioctl@noreply.github.com> 
Cc: Zibri <zibri@zibri.org>,Author <author@noreply.github.com> 
Oggetto: Re: [jerome-pouiller/ioctl] Missing feature: IOCTL for network
  devices (#6) 

I would be glad to receive your patch.

However, since there are no file devices associated to network interfaces, how do you suggest to implement that? We may think about a generic solution since we may want to add support for other kind of resources in future.

**Comment by eugene-bright** [comment]
I'm not experienced in this subject, but `man netdevice` says that we can use network device ioctl `on any socket's file descriptor regardless of the family or type`.
Does it mean that we can apply corresponding ioctl on any unix socket and get for instance list of network devices from it?

**Comment by jerome-pouiller** [comment]
>  Does it mean that we can apply corresponding ioctl on any unix socket and get for instance list of network devices from it?

Yes, I believe.
