### ISSUE TITLE
Cache ioctls into an h file as numbers

### ISSUE THREAD

**Issue by KOLANICH** [jerome-pouiller/ioctl#7]
Currently the stuff requires lots of headers to be installed.

The solution is to create a file with exact numeric values of ioctls, so a user doesn't have to install the packages with headers.

**Comment by jerome-pouiller** [comment]
I reworked the `ioctl_list.c`. All header it now includes are provided by linux kernel uapi (provided by the package `linux-libc-dev` on debian-like). I have checked it with:

    for i in $(grep '#include <' ioctls_list.c | sed -e 's/#include <//' -e 's/>//'); do
        dpkg -L linux-libc-dev | grep -q $i || echo $i ko
    done

Reopen the bug if you have difficulties with compilation.

**Comment by KOLANICH** [comment]
Thank you.
